# Generated by Django 4.1.5 on 2023-02-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowmyclass", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="university",
        ),
        migrations.DeleteModel(
            name="University",
        ),
    ]
