# Generated by Django 4.1.5 on 2023-02-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowmyclass", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="course",
            name="credits",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="course",
            name="other",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="prerequisites",
            field=models.TextField(null=True),
        ),
    ]
