# Generated by Django 4.1.5 on 2023-02-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowmyclass", "0002_alter_course_course_name_alter_course_credits_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
