# Generated by Django 4.1.5 on 2023-02-26 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("knowmyclass", "0004_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Professor_course",
            fields=[
                (
                    "professor_course_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "course_overall_rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                (
                    "professor_overall_rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                (
                    "difficulty_overall_rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                ("course_summary", models.TextField(null=True)),
                ("professor_summary", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "course_rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                (
                    "professor_rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                (
                    "difficulty_rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                ("course_review", models.TextField(null=True)),
                ("professor_review", models.TextField(null=True)),
                ("suggestion_review", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "professor_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowmyclass.professor_course",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
