# Generated by Django 4.1.5 on 2023-02-26 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("knowmyclass", "0005_professor_course_review_delete_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="professor_course",
            name="course_name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="knowmyclass.course",
            ),
            preserve_default=False,
        ),
    ]
