# Generated by Django 4.1.5 on 2023-03-01 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowmyclass", "0006_professor_course_course_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="professor_course",
            old_name="course_name",
            new_name="course",
        ),
    ]
